### ISSUE TITLE
全局模式没有了，通过修改分流规则实现

### ISSUE THREAD

**Issue by duqn** [xiaorouji/openwrt-passwall2#139]
做旁路由使用，主路由分流过来的流量，不能全部转发，给分流规则 Proxy 里添加 geoip或geosite规则后，没效果

**Comment by duqn** [comment]
查了一下passwall2 用的配置/usr/share/passwall2/rule_update.lua，知道geoip和geosite库的来源来自Loyalsoldier/v2ray-rules-dat，于是发现找到 geoip:!cn 排除国区IP，添加到passwall2 Proxy分流规则解决了

**Comment by duqn** [comment]
Proxy: > IP
geoip:!cn

**Comment by Recoba86** [comment]
I'm not in china
so I should put GeoIP:!country-code in the proxy section right?

**Comment by Recoba86** [comment]
> right

Thanks
btw, do you know any way to solve WhatsApp calls or any other call problems?
when I test through Twilio test show an error
![202530686-683190c2-a949-4308-8f41-7705a762a5f6](https://user-images.githubusercontent.com/70960815/202544084-12cddf5d-f3f0-4b1f-8f52-e75903f9c2e1.png)

**Comment by duqn** [comment]
Proxy: > Domain
geosite:whatsapp
domain:whatsapp.com
--------or
Proxy: > IP
geoip:whatsapp
--------or
geoip:x.x.x.x
Ex. https://ipinfo.io/AS11917

**Comment by Recoba86** [comment]
no that's not the case
Whatsapp text chat or anything works like a charm
so data goes through Proxy but audio and video call is not working
not only WhatsApp, same for telegram ,google meet, or any other audio call app
It's something with UDP problem with passwall!
because the same server in android in matsuri app work without a problem

**Comment by duqn** [comment]
DNS 问题

**Comment by Recoba86** [comment]
what dns mode should i use?
its using xray adguard
should i chnage it to anything?
